//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DvbIpTv.Setup.UpdateWolf424.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.DvbIpTv.Setup.UpdateWolf424.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update was interrupted or has failed and {0} has not been properly updated properly. It is quite possible that it might be unusable.
        ///Try updating again and if the problem persists, completely uninstall the product and install the full updated version.
        ///
        ///Select &apos;Finish&apos; to exit the Update Wizard..
        /// </summary>
        internal static string EndTextAbort {
            get {
                return ResourceManager.GetString("EndTextAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} update was interrupted.
        ///Your system has not been modified. To install this program at a later time, please run the wizard again.
        ///
        ///Select &apos;Finish&apos; to exit the Update Wizard..
        /// </summary>
        internal static string EndTextCancel {
            get {
                return ResourceManager.GetString("EndTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully updated to {1}.
        ///
        ///Select &apos;Finish&apos; to exit the Update Wizard..
        /// </summary>
        internal static string EndTextOk {
            get {
                return ResourceManager.GetString("EndTextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Update Wizard was interrupted.
        /// </summary>
        internal static string EndTitleAbort {
            get {
                return ResourceManager.GetString("EndTitleAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Update Wizard was cancelled.
        /// </summary>
        internal static string EndTitleCancel {
            get {
                return ResourceManager.GetString("EndTitleCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed the {0} Update Wizard.
        /// </summary>
        internal static string EndTitleOk {
            get {
                return ResourceManager.GetString("EndTitleOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exclamation_64x64 {
            get {
                object obj = ResourceManager.GetObject("Exclamation_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang3082{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil\fcharset2 Symbol;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\nowidctlpar\sa200\sl276\slmult1\qj\lang10\b\f0\fs20 movistar+ DVB-IPTV decoder version 1.0 \ldblquote Wolf 424\rdblquote  Update 1\ul\fs18\par
        ///NOTICE:\ulnone\b0  \b\i This software IS NOT SUPPORTED NOR ENDORSED by Movistar or Telef\&apos;f3nica\b0\i0 . Telef\&apos;f3nica de Espa\&apos;f1a has no responsibility if there a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseAgreement {
            get {
                return ResourceManager.GetString("LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon QuestionIcon {
            get {
                object obj = ResourceManager.GetObject("QuestionIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movistar TV Decoder 1.0 “Wolf 424”.
        /// </summary>
        internal static string TargetProductName {
            get {
                return ResourceManager.GetString("TargetProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TickGreen_64x64 {
            get {
                object obj = ResourceManager.GetObject("TickGreen_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon UpdateIcon {
            get {
                object obj = ResourceManager.GetObject("UpdateIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movistar+ Decoder 1.0 “Wolf 424” with Update 1.
        /// </summary>
        internal static string UpdateProductName {
            get {
                return ResourceManager.GetString("UpdateProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning_64x64 {
            get {
                object obj = ResourceManager.GetObject("Warning_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WizardSide {
            get {
                object obj = ResourceManager.GetObject("WizardSide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WizardSidePattern {
            get {
                object obj = ResourceManager.GetObject("WizardSidePattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WizardTop {
            get {
                object obj = ResourceManager.GetObject("WizardTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
